{{ config(database="MHA_DATA") }}

SELECT "ANYBRANCH"
      ,"AUTORENEW"
      ,"AVAILABLE"
      ,"DESCRIPTION"
      ,"MAX"
      ,"PROGRAMTYPE"
      ,"PROGRAMCODE"
      ,"PROGRAMDEFINITIONID"
      ,"PROGRAMSPECIAL"
FROM "FIVETRAN_DATABASE"."STAGE_DBO"."PROGRAMCODE"