{{ config(database="MHA_DATA") }}
{{ config(materialized="table") }}

SELECT "AVERAGEPRICE"
      ,"AVERAGETIME"
      ,"BILLINGTYPE"
      ,"CALLBACKDATE"
      ,"CANCELCODE"
      ,"CANCELDATE"
      ,"CANCELEDBY"
      ,"CONFIRMATIONDATE"
      ,"CONFIRMEDBY"
      ,"CONTACTDATE"
      ,"CREATED"
      ,"CUSTOMERNUMBER"
      ,"DATESOLD"
      ,"DAYCODE"
      ,"DIFFICULTY"
      ,"DONETODATE"
      ,"ENDON"
      ,"ESTIMATEDBY"
      ,"ESTIMATEREQUESTDATE"
      ,"ESTIMATEREQUESTTAKENBY"
      ,"HOLDBEGINDATE"
      ,"HOLDCODE"
      ,"HOLDDATE"
      ,"ID"
      ,"ISAUTORENEW"
      ,"ISCOMPLETE"
      ,"ISFULLPROGRAM"
      ,"ISNONSERVICEYEAR"
      ,"ISPROGRAM"
      ,"ISRENEWED"
      ,"ISWORKORDER"
      ,"LASTPRICECHANGE"
      ,"LATESTDEPENDENTSERVICECOMPLETIONDATE"
      ,"MAXIMUMREPETITIONS"
      ,"NEXTDATE"
      ,"NUMBEROFSERVICES"
       ,"PRICE"
      ,"PROGRAMCODE"
      ,"PROGRAMCODEID"
      ,"ROUTE"
      ,"SEASON"
      ,"SIZE"
      ,"SOLDBY1"
      ,"SOLDBY2"
      ,"SOURCECODE"
      ,"STANDARDPRICE"
      ,"STARTYEAR"
      ,"STATUS"
      ,"UPDATED"
      ,"WORKORDERPRICING"
FROM "FIVETRAN_DATABASE"."STAGE_DBO"."PROGRAM"