{{ config(database="MHA_DATA") }}

SELECT "ACTIVEORPASSIVE"
      ,"ANYBRANCH"
      ,"AVAILABLE"
      ,"HANDHELD"
      ,"ID"
      ,"SOURCEABBREVIATION"
      ,"SOURCEDESCRIPTION"
FROM "FIVETRAN_DATABASE"."STAGE_DBO"."SOURCECODE"